//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.07 at 04:50:12 PM COT 
//

package co.swatit.pilautil.dto.in;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import co.swatit.pilautil.dto.RequestDTO;

/**
 * <p>
 * Objeto de transporte que contiene los parámetros de entrada del servicio web getContributorsInformation
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getContributorsInformationInDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{}requestDTO">
 *       &lt;sequence>
 *         &lt;element name="contributorsIds" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getContributorsInformationInDTO", propOrder = { "contributorsIds" })
public class GetContributorsInformationInDTO extends RequestDTO {

	/**
	 * Constante de serialización
	 */
	private static final long serialVersionUID = 1L;

	@XmlElement(nillable = true)
	private List<String> contributorsIds;

	/**
	 * Gets the value of the contributorsIds property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make
	 * to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the contributorsIds property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContributorsIds().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getContributorsIds() {
		if (contributorsIds == null) {
			contributorsIds = new ArrayList<String>();
		}
		return this.contributorsIds;
	}

}
